# Generated by Django 4.2.7 on 2024-04-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Preço',
            new_name='Preco',
        ),
    ]
